### ISSUE TITLE
Can't launch: CRITICAL Qt: Cannot mix incompatible Qt library (6.7.1) with this library (6.7.2)

### ISSUE THREAD

**Issue by Deevad** [flathub/org.beeref.BeeRef#65]
Hey, since the end of last week, I can't launch BeeRef anymore, help! 😅

Log in a terminal:
```
~ »»» flatpak run org.beeref.BeeRef
INFO __main__: Starting BeeRef version 0.3.3
INFO __main__: Using settings: /home/deevad/.var/app/org.beeref.BeeRef/config/BeeRef/BeeRef.ini
INFO __main__: Logging to: /home/deevad/.var/app/org.beeref.BeeRef/config/BeeRef/BeeRef.log
CRITICAL Qt: Cannot mix incompatible Qt library (6.7.1) with this library (6.7.2)
```

Version:
```
~ »»» flatpak list
BeeRef                                      org.beeref.BeeRef                            0.3.3          stable           system
KDE Application Platform                    org.kde.Platform                                            5.15-23.08       system
KDE Application Platform                    org.kde.Platform                                            6.6              system
KDE Application Platform                    org.kde.Platform                                            6.7              system
KDE                                         org.kde.kdenlive                             24.05.1        stable           system
```

commit log hasn't changed since a big month, so I think rolling back is useless in this case:
```
~ »»» flatpak remote-info --log flathub org.beeref.BeeRef
        ID: org.beeref.BeeRef
       Ref: app/org.beeref.BeeRef/x86_64/stable
      Arch: x86_64
    Branch: stable
Collection: org.flathub.Stable
  Download: 278.4 MB
 Installed: 624.7 MB
   Runtime: org.kde.Platform/x86_64/6.7
       Sdk: org.kde.Sdk/x86_64/6.7

    Commit: bf5b74f9f261c4e25137cb8ed0f99f6050625352eadf53a9bc5b2158965be02f
    Parent: b1b587a7e05a163bffc3658583e2105f1b30dffedc8be7db08e37f06e42e1428
   Subject: Update KDE runtime (15bf1b50)
      Date: 2024-05-27 01:03:28 +0000
   History: 

    Commit: b1b587a7e05a163bffc3658583e2105f1b30dffedc8be7db08e37f06e42e1428
   Subject: Automatically merge Flathub bot PRs (af311b4b)
      Date: 2024-05-23 21:44:44 +0000

    Commit: a6ffa9a41fc4a46161e4de2c75aa3a20e0717895be1b979359b61239c7ac5923
   Subject: appdata: Fix screenshot-no-media error (cc67a23c)
      Date: 2024-05-23 20:57:41 +0000

    Commit: 938e64eca597b375b484a15b2b6f5f24de715215b077fe3527fa359f92b213f4
   Subject: Update beeref.git to 0.3.1 (52e2660e)
      Date: 2023-12-11 00:50:02 +0000

    Commit: 5914871a770c67d9994286a14a8012e5f65b70084aafb67c3fb336bfba2bf1ab
   Subject: Update beeref.git to 0.3.0 (54b8dbfd)
      Date: 2023-11-26 19:50:40 +0000

    Commit: 2d99eb805005d09ba6fd11c99a4e1d9da84951cde2c9147125573888a4876b9b
   Subject: Add x-data-checker so flathubbot can update the project automatically (e7e15bb7)
      Date: 2022-07-22 18:40:12 +0000

    Commit: e5a1f07b95e13dd4f31d494d339b98b8d6faaf2318258d806a2461440535fded
   Subject: Add x-data-checker so flathubbot can update the project automatically (e7e15bb7)
      Date: 2022-07-22 18:40:12 +0000
```
